### ISSUE TITLE
Error deserializing response after call to create bucket via InfluxDB java client?

### ISSUE THREAD

**Issue by Luckvery** [influxdata/influxdb-client-java#115]
Attempting to dynamically create a bucket, I keep receiving the following error.

Error: 
```
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 233 path $.labels
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.6.jar:na]
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39) ~[converter-gson-2.5.0.jar:na]
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) ~[converter-gson-2.5.0.jar:na]
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223) ~[retrofit-2.5.0.jar:na]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[retrofit-2.5.0.jar:na]
        at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:76) ~[influxdb-client-core-1.8.0.jar:1.8.0]
        at com.influxdb.client.internal.BucketsApiImpl.createBucket(BucketsApiImpl.java:196) ~[influxdb-client-java-1.8.0.jar:1.8.0]
```

OkHttp Logs prior to error: 
```
: --> POST http://localhost:9999/api/v2/api/v2/buckets
: Content-Type: application/json
: Content-Length: 136
: User-Agent: influxdb-client-java/1.8.0
: 
: {"orgID":"Cool Company","name":"candles","description":"Dynamically created bucket","retentionRules":[{"type":"expire","everySeconds":900}]}
: --> END POST (136-byte body)
: <-- 200 OK http://localhost:9999/api/v2/api/v2/buckets (33ms)
: Content-Type: application/json; charset=utf-8
: Date: Sat, 23 May 2020 16:45:55 GMT
: Content-Length: 907
: 
: {"authorizations":"/api/v2/authorizations","buckets":"/api/v2/buckets","checks":"/api/v2/checks","dashboards":"/api/v2/dashboards","delete":"/api/v2/delete","external":{"statusFeed":"https://www.influxdata.com/feed/json"},"labels":"/api/v2/labels","me":"/api/v2/me","notificationEndpoints":"/api/v2/notificationEndpoints","notificationRules":"/api/v2/notificationRules","orgs":"/api/v2/orgs","query":{"analyze":"/api/v2/query/analyze","ast":"/api/v2/query/ast","self":"/api/v2/query","suggestions":"/api/v2/query/suggestions"},"scrapers":"/api/v2/scrapers","setup":"/api/v2/setup","signin":"/api/v2/signin","signout":"/api/v2/signout","sources":"/api/v2/sources","swagger":"/api/v2/swagger.json","system":{"debug":"/debug/pprof","health":"/health","metrics":"/metrics"},"tasks":"/api/v2/tasks","telegrafs":"/api/v2/telegrafs","users":"/api/v2/users","variables":"/api/v2/variables","write":"/api/v2/write"}

: <-- END HTTP (907-byte body)

```

Code: 
```
 private fun dynamicallyCreateBucket(
            bucketName: String,
            influxDBClient: InfluxDBClient,
            org: String
    ) {
        val bucket: Bucket = createBucket(
                bucketName = bucketName,
                orgId = org,
                influxDBClient = influxDBClient
        )
    }

    private fun createBucket(
            bucketName: String,
            orgId: String,
            influxDBClient: InfluxDBClient
    ): Bucket =
            PostBucketRequest()
                    .description("Dynamically created bucket")
                    .name(bucketName)
                    .orgID(orgId)
                    .addRetentionRulesItem(BucketRetentionRules().everySeconds(900))
                    .let {
                        influxDBClient.bucketsApi.createBucket(
                                bucketName,
                                BucketRetentionRules().everySeconds(900),
                                orgId
                        )
                    }
```

Version:
```  implementation("com.influxdb:influxdb-client-java:1.8.0")```

Note: I tried ```  implementation("com.influxdb:influxdb-spring:1.8.0")``` with a slightly different configuration and received the same error 🤷. I am able to initialize `InfluxDBClient` connecting to an existing bucking without any problems. 

[SO](https://stackoverflow.com/questions/61977541/error-deserializing-response-after-call-to-create-bucket-via-influxdb-java-2-0-c)

**Comment by sranka** [comment]
@Luckvery http://localhost:9999/api/v2/api/v2/buckets  wrong, creating InfluxDBClient using url without "/api/v2" path might help

**Comment by Luckvery** [comment]
@sranka My mistake!! Thank you very much for your reply and help.

I am now seeing ` {"code":"invalid","message":"id must have a length of 16 bytes"}`. I thought this issue was resolved #13906 or is it unrelated?

**Comment by sranka** [comment]
@Luckvery `orgId` should be an id of your organization (such as `fe941a3875dd5b68`), it is in the browser URL when you login into InfluxDB UI.

**Comment by Luckvery** [comment]
Thank you for your speedy response and help getting me unblocked 💪
