### ISSUE TITLE
Dependencies Issue with java-client

### ISSUE THREAD

**Issue by tinin007k** [influxdata/influxdb-client-java#121]
Using the influxdb-client-java - https://github.com/influxdata/influxdb-client-java. I am facing issue with okhttp & okio deps. I have added both in maven project with versions -> okhttp - 4.6.0 & okio - 2.6.0 still facing this issue
Exception in thread "main" java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:72)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)

**Comment by tinin007k** [comment]
This is a maven-scala project. Is there any limitations with this?

**Comment by bednar** [comment]
Hi @tinin007k,

thanks for using our client. There isn't limitations about use maven and scala.

Please, check that you have imported only one version of `okhttp` and `okio` by:

```bash
mvn dependency:tree -U
```

The current snapshot version of client depends on:

- `com.squareup.okio:okio:jar:2.6.0`
- `com.squareup.okhttp3:okhttp:jar:4.6.0` 

Regards
