### ISSUE TITLE
limit offset  param  maybe  is number 0

### ISSUE THREAD

**Issue by gemron** [influxdata/influxdb-client-java#160]
__Expected behavior:__
limit offset maybe  is number 0

__Actual behavior:__
when i set this offset param 0 value , throw a Exception like this:

Caused by: java.lang.IllegalArgumentException: Expecting a positive number for The number of records to skip
	at com.influxdb.Arguments.checkPositiveNumber(Arguments.java:123)
	at com.influxdb.query.dsl.functions.LimitFlux.withOffset(LimitFlux.java:81)
	at com.influxdb.query.dsl.Flux.limit(Flux.java:989)

__Specifications:__
 - Client Version: 1.12.0
 - InfluxDB Version: 2.0.0.rc0
 - JDK Version: 1.8
 - Platform: macos

**Comment by bednar** [comment]
@gemron thanks, we will take a look
