### ISSUE TITLE
Restriction has got a bug

### ISSUE THREAD

**Issue by coditori** [influxdata/influxdb-client-java#188]
When I run this test [FilterFluxTest.java](https://github.com/influxdata/influxdb-client-java/blob/1d943fb4dfa6d6fc4d7e4cf7aaac1e890b4cd536/flux-dsl/src/test/java/com/influxdb/query/dsl/functions/FilterFluxTest.java#L112) I get this error: "unsupported binary expression time <= duration"

I'm using Influx2 and flux-dsl

**Comment by bednar** [comment]
Hi @coditori,

I've try the `FilterFluxTest.java` and everything works fine. Could you share a full stack trace?

Regards

**Comment by coditori** [comment]
Hi @bednar 
I just used this block of code:
```
Flux.from("bucket")
                .range(-5L, ChronoUnit.YEARS)
                .filter(Restrictions.time().lessOrEqual(new TimeInterval(-15L, ChronoUnit.HOURS)))
```

Then got this error:
```
Exception in thread "main" com.influxdb.exceptions.BadRequestException: runtime error @3:5-3:42: filter: cannot compile @ 3:16-3:41: unsupported binary expression time <= duration
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:96)
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:145)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:193)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:104)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:803)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:83)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:73)
```

The time column is the fine, I wonder why it can not compare it with "TimeInterval"

**Comment by bednar** [comment]
It is an error from InfluxDB, you cannot compare `time` and `duration`:

![image](https://user-images.githubusercontent.com/455137/101600165-33966180-39fb-11eb-97bb-ab4cda926a30.png)

Regards

**Comment by coditori** [comment]
Hi @bednar
Yeah you right, then we should wait for the influxDB new release?

**Comment by bednar** [comment]
I don't think so. You should compare with the `date`:

```java
Flux flux = Flux.from("my-bucket")
       .range(-5L, ChronoUnit.YEARS)
       .filter(Restrictions.time().lessOrEqual(Instant.now().minus(-15L, ChronoUnit.HOURS)));
```
