### ISSUE TITLE
com.influxdb.exceptions.InfluxException: Read timed out

### ISSUE THREAD

**Issue by xwx606986** [influxdata/influxdb-client-java#193]
<!--

Thank you for reporting a bug. 

com.influxdb.exceptions.InfluxException: Read timed out
	at com.influxdb.internal.AbstractQueryApi.lambda$static$1(AbstractQueryApi.java:72)
	at com.influxdb.internal.AbstractRestClient.catchOrPropagateException(AbstractRestClient.java:142)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:195)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:104)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:803)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:83)
	at com.gaiaworks.microservice.controlpanel.impl.InfluxDBServiceImpl.getQuery(InfluxDBServiceImpl.java:66)
	at com.gaiaworks.microservice.controlpanel.impl.InfluxDBServiceImpl.getServiceQps(InfluxDBServiceImpl.java:271)
	at com.gaiaworks.microservice.controlpanel.impl.InfluxDBServiceImpl$$FastClassBySpringCGLIB$$52d22d90.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.gaiaworks.microservice.controlpanel.impl.InfluxDBServiceImpl$$EnhancerBySpringCGLIB$$2ab7040f.getServiceQps(<generated>)
	at com.gaiaworks.microservice.controlpanel.controller.MetricsController.getAqsFromInfluceDB(MetricsController.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version:1.10.0
 - InfluxDB Version:
 - JDK Version:1.8
 - Platform:

**Comment by bednar** [comment]
Hi @xwx606986,

You could also customize HTTP connection timeouts via:

```java
OkHttpClient.Builder builder = new OkHttpClient.Builder()
    .readTimeout(30, TimeUnit.SECONDS)
    .writeTimeout(30, TimeUnit.SECONDS)
    .connectTimeout(30, TimeUnit.SECONDS);

InfluxDBClientOptions options = InfluxDBClientOptions.builder()
    .url("http://localhost:8086")
    .authenticateToken("my-token".toCharArray())
    .okHttpClient(builder)
    .build();

InfluxDBClient client = InfluxDBClientFactory.create(options);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
