### ISSUE TITLE
java.lang.IllegalAccessError tried to access method com.google.gson.Gson.newJsonWriter

### ISSUE THREAD

**Issue by stepanurban** [influxdata/influxdb-client-java#204]
Hi,
I'm using influxdb-client-java:2.0.0 library from Spark in Scala with
`InfluxDBClientFactory.create("http://cluster.local:8086", token.toCharArray).getQueryApi.query("from(bucket: \"test\")", org);`
but getting following exception
`java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
  at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:46)
  at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30)
  at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:429)
  at retrofit2.RequestFactory.create(RequestFactory.java:129)
  at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:208)
  at retrofit2.OkHttpCall.getRawCall(OkHttpCall.java:107)
  at retrofit2.OkHttpCall.execute(OkHttpCall.java:197)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:237)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:190)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:122)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:803)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:83)`

Spark version:2.4.6
Scala version:version 2.11.12

I'm I doing something wrong?

Thank you

**Comment by bednar** [comment]
Hi @stepanurban,

thanks for using our client. It looks like conflict with `gson` versioning.

The library depends on `com.google.code.gson:gson:jar:2.8.5`.

Could you check that you use correct version of `gson`? You could print all your dependencies by: `mvn dependency:tree`.

Regards

**Comment by stepanurban** [comment]
Hi @bednar,
ok when sending the job there is correct version but later probably not. I need to investigate how to solve these dependency problems in Spark.
Thank you

**Comment by bednar** [comment]
@stepanurban, can you share your solution. It could be useful for other users.

**Comment by fantasticmao** [comment]
@bednar The `com.google.gson.Gson#newJsonWriter` method was changed to public on 09/27/2015, so the Gson version should be greater or equals than `2.4`.

Check this commit: https://github.com/google/gson/commit/e81f3eba2731bac5b7b5a50e7218f9847a170d83

**Comment by bednar** [comment]
@fantasticmao the client depends on `2.8.8` - https://github.com/influxdata/influxdb-client-java/blob/62c9a1ee3820d52e690aa3fd864bb91c52c4259e/pom.xml#L113

**Comment by fantasticmao** [comment]
@bednar I know, I just want to tell others how to solve this problem when they get dependency conflict :)
