### ISSUE TITLE
Error: "short write" when writing points

### ISSUE THREAD

**Issue by SadSadko** [influxdata/influxdb-client-java#230]
Hi,
I'm using Spark Structured Streaming app to write points to InfluxDB, and occasionally it fails with "short write" error (once every few weeks) I cant understand why or what does it even mean.
I tried to update to the latest version (2.2.0) but it didn't help.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
running the Spark Streaming application, every micro-batch, I flush and then closing the WriteAPI and InfluxDBClient.
(Using Spark ForeachWriter)

__Expected behavior:__
the data stays the same So I don't expect any errors, and if so I expect a more informed error.

__Actual behavior:__
Points writing is failing once in a while for a certain period of time (can be hours). restarts does not help.

__Specifications:__
 - Client Version: 2.2.0
 - InfluxDB Version: 1.8.3
 - JDK Version: 11
 - Platform:

**Comment by bednar** [comment]
Hi @SadSadko,

thanks for using our client. 

Do you have a stack trace with detail information? How looks like your InfluxDB log?

Regards

**Comment by SadSadko** [comment]
Hi bednar,
this is the stack trace: 
`21/06/03 10:27:18 ERROR WriteErrorEvent: The error occurred during writing of data
com.influxdb.exceptions.InternalServerErrorException: short write
at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:118)
at com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:543)
at com.influxdb.client.internal.AbstractWriteClient.lambda$new$12(AbstractWriteClient.java:178)
at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:84)
at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284)
at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.innerSuccess(FlowableConcatMapMaybe.java:179)
at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber$ConcatMapMaybeObserver.onSuccess(FlowableConcatMapMaybe.java:322)
at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver$NextMaybeObserver.onSuccess(MaybeOnErrorNext.java:134)
at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onError(MaybeOnErrorNext.java:109)
at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
at io.reactivex.internal.operators.flowable.FlowableSingleMaybe$SingleElementSubscriber.onError(FlowableSingleMaybe.java:89)
at io.reactivex.subscribers.SerializedSubscriber.onError(SerializedSubscriber.java:142)
at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onError(FlowableRepeatWhen.java:112)
at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:572)
at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:379)
at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:313)
at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
at io.reactivex.internal.operators.flowable.FlowableDelay$DelaySubscriber$OnNext.run(FlowableDelay.java:114)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)`

it will take me few minutes to get the InfluxDB logs.

**Comment by bednar** [comment]
It looks like problem with writing data into file system. The error comes from: https://github.com/influxdata/influxdb/blob/dee8977d2c6598cb2d17e9334ea997c99853640a/tsdb/engine/tsm1/writer.go#L399

Do you have enough space on a disk device for InfuxDB?

> running the Spark Streaming application, every micro-batch, I flush and then closing the WriteAPI and InfluxDBClient.

The `WriteApiBlocking` will be better for this purpose. It will avoid unnecessary batching and you can use `WriteApiBlocking` as a singleton.

- https://golang.org/pkg/io/
- https://github.com/influxdata/influxdb/commit/2ab0a8379343164fc1b1e3ac775a89ad5dec6877

**Comment by SadSadko** [comment]
Hi,
So there was enough space on the disk, after a restart to the Influx server it was resolved.
sorry, I don't have access to the logs, why would WriteApiBlock be better?

**Comment by bednar** [comment]
> I don't have access to the logs, why would WriteApiBlock be better?

The `WriteApi` is suppose to run as a long live singleton. I think that the `Spark ForeachWriter` strongly depends on result of write request = You need to know if write fails or not, immediately. For this requirements is better to use `WriteApiBlocking`, because it avoid unnecessary background buffering and it directly writes data into InfluxDB.

**Comment by SadSadko** [comment]
Interesting point, however according to ForeachWriter documentation
![image](https://user-images.githubusercontent.com/81636942/120982266-2aefcf80-c781-11eb-8ac9-8670c87b6b5f.png)
in case there are multiple rows in a partition and batch the method process is called, so I can benefit from the background buffering right?

**Comment by bednar** [comment]
> in case there are multiple rows
Yes, you are right.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
