### ISSUE TITLE
unnamed module reads package com.incluxdb from both incluxdb.client.core and incluxdb.client.utils

### ISSUE THREAD

**Issue by White-Lee** [influxdata/influxdb-client-java#270]
Hi all,

1. add module-info
2. run the demo

 my `module-info.java` file like this
```java
 module xxx.xxx{
    requires influxdb.client.java;
    requires influxdb.client.core;
    requires influxdb.client.utils;
}
```
after run the demo program  i got 
`java: unnamed module reads package com.incluxdb from both incluxdb.client.core and incluxdb.client.utils`
but when i change Client Version to `3.2.0` the error gone

 - Client Version: 3.3.0
 - InfluxDB Version: 2.0.8
 - JDK Version: 17
 - Platform: macOS

**Comment by bednar** [comment]
Why your module definition contains `influxdb.client.core` and `influxdb.client.util`? 

I think you can use only `influxdb.client.java`. Try to test your `module-info.java` like this:

```java
module xxx.xxx{
    requires influxdb.client.java;
}
```

**Comment by White-Lee** [comment]
Thanks for your reply @bednar ,

1. The [By POJO](https://github.com/influxdata/influxdb-client-java/tree/master/client#by-pojo) example need `influxdb.client.core`.
![image](https://user-images.githubusercontent.com/19421557/138219584-db9caa04-b2b8-4f0e-bddb-81d721273aaf.png)

2. Whitout `influxdb.client.util` when i run [InfluxDB2ManagementExample](https://github.com/influxdata/influxdb-client-java/tree/master/client#management-api) I got this error
``` java
Exception in thread "main" java.lang.NoClassDefFoundError: com/influxdb/Arguments
	at influxdb.client.java@3.3.0/com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:232)
	at influxdb.client.java@3.3.0/com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:153)
	at org.zr.crayfish/org.zr.crayfish.client.InfluxDB2ManagementExample.main(InfluxDB2ManagementExample.java:21)
Caused by: java.lang.ClassNotFoundException: com.influxdb.Arguments
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more
```
and the `Arguments.java`  are included in `influxdb.client.util`
![image](https://user-images.githubusercontent.com/19421557/138219155-c12d7444-ff2a-4c14-82d3-4f31cae9d2ad.png)
so i add it in my `module-info.java`.
