### ISSUE TITLE
Cloud2 query throws FluxCsvParserException

### ISSUE THREAD

**Issue by rhajek** [influxdata/influxdb-client-java#284]
Following query example is not working in cloud2.

The response contains:
```
,result,table,_start,_stop,_time,_value,_field,_measurement,location
,_result,0,2021-11-24T10:28:30.128977253Z,2021-12-01T10:28:30.128977253Z,2021-11-26T14:06:43.833846Z,1.12345,level,h2o,Prague
```

__Steps to reproduce:__
```java
        Query query = new Query().query("from(bucket: params.mybucket) |> range(start: -7d) |> limit(n:2)")
            .putParamsItem("mybucket", "my-bucket");

        String url = "https://us-west-2-1.aws.cloud2.influxdata.com";
        String authToken =
            "...";
        String org = "...";

        influxDBClient = InfluxDBClientFactory.create(url, authToken.toCharArray(), org);
        influxDBClient.setLogLevel(LogLevel.BODY);

        QueryApi queryApi = influxDBClient.getQueryApi();

        List<FluxTable> result = queryApi.query(query);
        result.forEach(System.out::println);

```
Log:
```
INFO: ,result,table,_start,_stop,_time,_value,_field,_measurement,location
,_result,0,2021-11-24T10:28:30.128977253Z,2021-12-01T10:28:30.128977253Z,2021-11-26T14:06:43.833846Z,1.12345,level,h2o,Prague


Dec 01, 2021 11:28:30 AM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (199-byte body)

com.influxdb.query.exceptions.FluxCsvParserException: Unable to parse CSV response. FluxTable definition was not found.

	at com.influxdb.query.internal.FluxCsvParser.parseNextResponse(FluxCsvParser.java:200)
	at com.influxdb.query.internal.FluxCsvParser.parseFluxResponse(FluxCsvParser.java:140)
	at com.influxdb.internal.AbstractQueryApi.lambda$query$2(AbstractQueryApi.java:116)
	at com.influxdb.internal.AbstractQueryApi.lambda$query$5(AbstractQueryApi.java:174)
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:220)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:238)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:190)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:122)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:802)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:92)
	at com.influxdb.client.ITQueryService.queryParameters(ITQueryService.java:189)
```

__Expected behavior:__
Should parse without error.

__Specifications:__
 - Client Version: latest master branch
 - InfluxDB Version: cloud 2
 - JDK Version: 17
 - Platform: Mac

**Comment by bednar** [comment]
The `Query` doesn't have specified dialect: `Query().query(query).dialect(AbstractInfluxDBClient.DEFAULT_DIALECT`.
