### ISSUE TITLE
BadRequestException is constructed without "error" detail.

### ISSUE THREAD

**Issue by rhajek** [influxdata/influxdb-client-java#31]
2019-05-13 09:28:18.087  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : --> POST http://localhost:9999/api/v2/query?orgID=my-org
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Content-Type: application/json
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Content-Length: 269
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Accept: text/csv
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : 
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : {"query":"from(bucket:\"my-bucket\")\n\t|> range(start:-10m)\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")","type":"flux","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}
2019-05-13 09:28:18.088  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : --> END POST (269-byte body)
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : <-- 400 Bad Request http://localhost:9999/api/v2/query?orgID=my-org (25ms)
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Content-Type: application/json; charset=utf-8
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : X-Platform-Error-Code: invalid
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Date: Mon, 13 May 2019 07:28:18 GMT
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : Content-Length: 132
2019-05-13 09:28:18.114  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : 
2019-05-13 09:28:18.115  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : **{"code":"invalid","message":"failed to decode request body","op":"http/handlePostQuery","error":"id must have a length of 16 bytes"}**
2019-05-13 09:28:18.115  INFO 65588 --- [           main] okhttp3.OkHttpClient                     : <-- END HTTP (132-byte body)

```
org.influxdata.exceptions.BadRequestException: failed to decode request body

	at org.influxdata.internal.AbstractRestClient.responseToError(AbstractRestClient.java:142)
	at org.influxdata.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:145)
	at org.influxdata.internal.AbstractQueryApi.query(AbstractQueryApi.java:193)
	at org.influxdata.internal.AbstractQueryApi.query(AbstractQueryApi.java:104)
	at org.influxdata.client.internal.QueryApiImpl.query(QueryApiImpl.java:803)
	at org.influxdata.client.internal.QueryApiImpl.query(QueryApiImpl.java:105)
	at org.influxdata.client.internal.QueryApiImpl.query(QueryApiImpl.java:83)
	at org.influxdata.client.internal.QueryApiImpl.query(QueryApiImpl.java:73)
	at io.bonitoo.influxdemo.test.InfluxDBServiceTest.testInfluxDBService(InfluxDBServiceTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

**Comment by mashintsev** [comment]
Query API url outdated.
Url in influxd 2.0.0-alpha.16 - http://localhost:9999/api/v2/query?**org**=my-org
Url in java client - http://localhost:9999/api/v2/query?orgID=my-org

**Comment by bednar** [comment]
It's fixed. The current version of InfluxDB 2.0 returns proper formatted error:

```
--> POST http://127.0.0.1:9999/api/v2/write?orgID=my-org&bucket=h2o1579768011524-IT&precision=ns

<-- 400 Bad Request http://127.0.0.1:9999/api/v2/write?orgID=my-org&bucket=h2o1579768011524-IT&precision=ns (3ms)
<-- X-Platform-Error-Code: invalid
<-- {"code":"invalid","message":"id must have a length of 16 bytes"}
``` 

```java
com.influxdb.exceptions.BadRequestException: id must have a length of 16 bytes
```
