### ISSUE TITLE
query result data type transform error

### ISSUE THREAD

**Issue by win434545299** [influxdata/influxdb-client-java#321]
__Steps to reproduce:__

1. the _value in the InfluxDB was Double

2. the field in my POJO was Double

3. query like this:

        String flux = "from(bucket: \"tx_test\") |> range(start: 0) |> filter(fn: (r) => r._measurement == " +
            "\"variable\")";

        List<Variable> values = influxDbHelper.queryApi().query(flux, Variable.class);

4. error:  
com.influxdb.exceptions.InfluxException: Can not set java.lang.Double field com.by.transform.domain.Variable.value to java.lang.Long

sorry for my bad English

__Specifications:__
 - Client Version: 5.0.0
 - InfluxDB Version: 2.0
 - JDK Version: zulu 1.8
 - Platform: macOS

**Comment by bednar** [comment]
Hi @win434545299,

thanks for using our client.

It looks like that the InfluxDB return `_value` as a `long`. 

Can you share a debug output of the client? You can enable debug by:

```java
client.setLogLevel(LogLevel.BODY);
```

Regards

**Comment by win434545299** [comment]
Thanks for your reply. this my log.

2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - --> POST http://xxx.xxx.xxx.xxx:8086/api/v2/query?org=by
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Content-Type: application/json; charset=UTF-8
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Content-Length: 277
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - User-Agent: influxdb-client-java/5.0.0
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - 
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - {"query":"from(bucket: \"sample_variable\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"variable\")","type":"flux","params":{},"dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - --> END POST (277-byte body)
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - <-- 200 OK http://xxx.xxx.xxx.xxx:8086/api/v2/query?org=by (103ms)
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Connection: close
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Transfer-Encoding: chunked
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Content-Type: text/csv; charset=utf-8
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Date: Wed, 30 Mar 2022 09:01:05 GMT
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - Vary: Accept-Encoding
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - 
2022-03-30 17:01:05 [main] INFO  okhttp3.OkHttpClient - #datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,0,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,1,type,variable,527

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,1,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,0,value,variable,527

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,2,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,1,type,variable,528

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,3,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,0,value,variable,528

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,4,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,1,type,variable,529

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,5,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,35,value,variable,529

..............

,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:43.752Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:44.757Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:46.782Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:49.807Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:51.828Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:52.841Z,0,type,variable,543
,,32,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T21:58:53.844Z,0,type,variable,543

......


com.influxdb.exceptions.InfluxException: Can not set java.lang.Float field com.by.transform.domain.Variable.value to java.lang.Long

	at com.influxdb.query.internal.FluxResultMapper.toPOJO(FluxResultMapper.java:98)
	at com.influxdb.client.internal.QueryApiImpl$1.accept(QueryApiImpl.java:200)
	at com.influxdb.query.internal.FluxCsvParser.parseFluxResponse(FluxCsvParser.java:145)
	at com.influxdb.internal.AbstractQueryApi.lambda$query$2(AbstractQueryApi.java:116)
	at com.influxdb.internal.AbstractQueryApi.lambda$query$5(AbstractQueryApi.java:174)
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:220)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:238)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:190)
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:122)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:204)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:147)
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:134)
	at com.by.test.InfluxDbTest.test(InfluxDbTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.Float field com.by.transform.domain.Variable.value to java.lang.Long
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.influxdb.query.internal.FluxResultMapper.setFieldValue(FluxResultMapper.java:160)
	at com.influxdb.query.internal.FluxResultMapper.toPOJO(FluxResultMapper.java:90)
	... 46 more

**Comment by bednar** [comment]
Your query results also contains long values:

```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#group,false,false,true,true,false,false,true,true,true
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,varId
,,4,1970-01-01T00:00:00Z,2022-03-30T09:01:05.923378671Z,2021-09-20T16:00:00Z,1,type,variable,529
```

You have to store all your data as double.

**Comment by win434545299** [comment]
thanks you, I have found the error, thank you again

**Comment by bednar** [comment]
The type in the `POJO` has to be same as in Flux query response.

**Comment by win434545299** [comment]
@bednar 
thank you very much
