### ISSUE TITLE
POJO type

### ISSUE THREAD

**Issue by yoobi** [influxdata/influxdb-client-java#326]
__Steps to reproduce:__
```
@Measurement(name = "measurement-test")
class Test {
    @Column(name = "tag_test", tag = true) var tagTest: Float = -1.0f
    @Column var field1: String = "no_set"
    @Column var field2: String = "no_set"
}

influxDBClient.writeApiBlocking.writeMeasurement(
            WritePrecision.MS,
            Test().apply {
                this.tagTest = tagTest
                this.field1 = field1
                this.field2 = field2
            })
```
what I got from reading is:
```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string
#group,false,false,true,true,false,true,true,false,false
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_measurement,tag_test,field1,field2
,,0,2022-04-07T19:24:19.741499Z,2022-04-07T20:24:19.741499Z,2022-04-07T20:21:30.978Z,measurement-test,1.33,fieeld,fiiiiiiiiiield


Caused by: java.lang.IllegalArgumentException: Can not set float field com.example.poccandlews.entity.Test.tagTest to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeFloatFieldAccessorImpl.set(UnsafeFloatFieldAccessorImpl.java:106) ~[na:na]
	at java.base/java.lang.reflect.Field.set(Field.java:799) ~[na:na]
	at com.influxdb.query.internal.FluxResultMapper.setFieldValue(FluxResultMapper.java:160) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.query.internal.FluxResultMapper.toPOJO(FluxResultMapper.java:90) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.client.internal.QueryApiImpl$1.accept(QueryApiImpl.java:200) ~[influxdb-client-java-5.0.0.jar:5.0.0]
	at com.influxdb.query.internal.FluxCsvParser.parseFluxResponse(FluxCsvParser.java:145) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi.lambda$query$2(AbstractQueryApi.java:116) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi.lambda$query$5(AbstractQueryApi.java:174) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:220) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:238) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:190) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:122) ~[influxdb-client-core-5.0.0.jar:5.0.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939) ~[influxdb-client-java-5.0.0.jar:5.0.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:204) ~[influxdb-client-java-5.0.0.jar:5.0.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:147) ~[influxdb-client-java-5.0.0.jar:5.0.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:134) ~[influxdb-client-java-5.0.0.jar:5.0.0]
```
__Expected behavior:__
Insert a Float and return a Float

__Actual behavior:__
I'm inserting a POJO which has 2 Strings and one Float, when I query my object I get 3 Strings

__Specifications:__
 - Java Client
 - Client Version: 5.0.0
 - InfluxDB Version: Influx CLI 2.3.0 (git: 88ba3464cd) build_date: 2022-03-18T22:21:12Z

**Comment by yoobi** [comment]
I was using `Float` type on a tag. 
According to doc tag value are always `String` https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#tag-value
