### ISSUE TITLE
when I use version 6.0.0, I am getting this exceptions,  kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by cuixin3266** [influxdata/influxdb-client-java#342]
`
import java.util.List;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.QueryApi;
import com.influxdb.query.FluxRecord;
import com.influxdb.query.FluxTable;

public class SynchronousQuery {

    private static final char[] token = "VbP83ofbBPZJpC8FmHxpl68Ali9eEZQ8hMoVJIuZ2rp86YcIuInXfnrh67QIq9gN9gYLS4J0GEoaZFgSUv87MA==".toCharArray();
    private static final String org = "xiaole";

    public static void main(final String[] args) {

        InfluxDBClient influxDBClient = InfluxDBClientFactory.create("http://localhost:8086", token, org);

        String flux = "from(bucket:\"my-bucket\") |> range(start: 0)";

        QueryApi queryApi = influxDBClient.getQueryApi();

        //
        // Query data
        //
        List<FluxTable> tables = queryApi.query(flux);
        for (FluxTable fluxTable : tables) {
            List<FluxRecord> records = fluxTable.getRecords();
            for (FluxRecord fluxRecord : records) {
                System.out.println(fluxRecord.getTime() + ": " + fluxRecord.getValueByKey("_value"));
            }
        }

        influxDBClient.close();
    }
}`

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I found this exception when I tried to write, but it still exists when I use the read function from the official document

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okio.Buffer.write(Buffer.kt)
	at okhttp3.ResponseBody.create(ResponseBody.java:214)
	at okhttp3.internal.Util.<clinit>(Util.java:69)
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.HttpUrl.parse(HttpUrl.java:905)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:644)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:636)
	at com.influxdb.client.InfluxDBClientOptions$Builder.connectionString(InfluxDBClientOptions.java:471)
	at com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:274)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:174)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:149)
	at com.lanshancloud.service.SynchronousQuery.main(SynchronousQuery.java:19)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more

2. Then when I try to reduce the version to 5.0.0, the exception does not exist and the program runs normally
3. 
__Expected behavior:__
Show something, or perform it normally

__Actual behavior:__
Exceptions were thrown

__Specifications:__
 - Client Version: 
    com.influxdb
    influxdb-client-java
    6.0.0
 - InfluxDB Version: 2.0.7
 - JDK Version: 1.8.0_281
 - Platform: docker
 - development environment: Windows10 & IntelliJ IDEA 2021.3

**Comment by bednar** [comment]
Hi @cuixin3266,

thanks for using our client. 

The version `6.0.0` has updated dependencies. 

How looks your project? Can you share your dependency tree? Do you use Maven or Gradle?

Regards

**Comment by bednar** [comment]
Which version Kotlin do you use?

**Comment by cuixin3266** [comment]
> Which version Kotlin do you use?

Kotlin version is IDEA built-in 1.5, the project uses Maven development, version 3.8.2
![QQ截图20220422125550](https://user-images.githubusercontent.com/37649800/164605932-71d3b88b-7055-4be5-a39e-68e9a71aca95.png)

**Comment by bednar** [comment]
Can you share whole dependency tree? You can use: `mvn dependency:tree`

**Comment by cuixin3266** [comment]
sorry
![QQ截图20220422131646](https://user-images.githubusercontent.com/37649800/164607970-0798d66e-fc17-4230-a831-223bfe9395db.png)

**Comment by cuixin3266** [comment]
I don't seem to see the influxdb dependency, what's wrong with this?

**Comment by bednar** [comment]
You probably ran the command in the wrong directory. 

Anyway... Can you test explicitly exclude `gson` from client dependency and add `gson` as a new dependency:

```xml
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.9.0</version>
</dependency>
<dependency>
    <groupId>com.influxdb</groupId>
    <artifactId>influxdb-client-java</artifactId>
    <version>6.0.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

?

**Comment by cuixin3266** [comment]
i try to do this, it's seem like doesn't work, and the dependency tree seem like normal
![9SD_8ZIK2`~T1BR3R`O2 }D](https://user-images.githubusercontent.com/37649800/164613228-b1615e58-d81a-40a9-a9a2-55fad9272ae3.png)
![EAP61AG96976XR{Q)0MU9CB](https://user-images.githubusercontent.com/37649800/164613241-63854bfe-afb6-4ad8-82f4-e194deb61427.png)

**Comment by cuixin3266** [comment]
Well, I don't know why every execution seems to have a different result， when i use: mvn dependency:tree
![QQ截图20220422140737](https://user-images.githubusercontent.com/37649800/164614069-af321c85-a596-4166-86f5-4135cf66d197.png)

**Comment by bednar** [comment]
> Well, I don't know why every execution seems to have a different result， when i use: mvn dependency:tree

This is very strange.

You can try find dependency version collision by: `mvn dependency:tree -U -Dverbose=true`

**Comment by cuixin3266** [comment]
I tried to delete other dependencies until I tested the springboot dependencies, I found that once I added this parent dependency, my project would report an error
``` java
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```
I tried to use different springboot version dependencies, and the results are all errors. When using 2.1.3.RELEASE, the following errors appear
```java
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:169)
	at okio.Segment.compact(Segment.kt:152)
	at okio.Buffer.write(Buffer.kt:1461)
	at okio.Buffer.read(Buffer.kt:1473)
	at okio.Buffer.writeAll(Buffer.kt:1260)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:189)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:175)
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
	at okio.Options$Companion.of(Options.kt:72)
	at okhttp3.internal.Util.<clinit>(Util.kt:70)
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
	at okhttp3.HttpUrl.parse(HttpUrl.kt)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:644)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:636)
	at com.influxdb.client.InfluxDBClientOptions$Builder.connectionString(InfluxDBClientOptions.java:471)
	at com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:274)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:174)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:149)
	at com.example.demo.SynchronousQuery.query(SynchronousQuery.java:81)
	at com.example.demo.SynchronousQuery.main(SynchronousQuery.java:19)
```
 When using 2.4.0 or 2.6.7, the following errors appear
```java
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okio.Buffer.write(Buffer.kt)
	at okhttp3.ResponseBody.create(ResponseBody.java:214)
	at okhttp3.internal.Util.<clinit>(Util.java:69)
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.HttpUrl.parse(HttpUrl.java:905)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:644)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:636)
	at com.influxdb.client.InfluxDBClientOptions$Builder.connectionString(InfluxDBClientOptions.java:471)
	at com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:274)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:174)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:149)
	at com.example.demo.SynchronousQuery.query(SynchronousQuery.java:81)
	at com.example.demo.SynchronousQuery.main(SynchronousQuery.java:19)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
```
when i remove the springboot parent dependency, i have right result

**Comment by xx13295** [comment]
> ` import java.util.List;
> 
> import com.influxdb.client.InfluxDBClient; import com.influxdb.client.InfluxDBClientFactory; import com.influxdb.client.QueryApi; import com.influxdb.query.FluxRecord; import com.influxdb.query.FluxTable;
> 
> public class SynchronousQuery {
> 
> ```
> private static final char[] token = "VbP83ofbBPZJpC8FmHxpl68Ali9eEZQ8hMoVJIuZ2rp86YcIuInXfnrh67QIq9gN9gYLS4J0GEoaZFgSUv87MA==".toCharArray();
> private static final String org = "xiaole";
> 
> public static void main(final String[] args) {
> 
>     InfluxDBClient influxDBClient = InfluxDBClientFactory.create("http://localhost:8086", token, org);
> 
>     String flux = "from(bucket:\"my-bucket\") |> range(start: 0)";
> 
>     QueryApi queryApi = influxDBClient.getQueryApi();
> 
>     //
>     // Query data
>     //
>     List<FluxTable> tables = queryApi.query(flux);
>     for (FluxTable fluxTable : tables) {
>         List<FluxRecord> records = fluxTable.getRecords();
>         for (FluxRecord fluxRecord : records) {
>             System.out.println(fluxRecord.getTime() + ": " + fluxRecord.getValueByKey("_value"));
>         }
>     }
> 
>     influxDBClient.close();
> }
> ```
> 
> }`
> 
> **Steps to reproduce:** List the minimal actions needed to reproduce the behavior.
> 
> 1. I found this exception when I tried to write, but it still exists when I use the read function from the official document
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics at okio.Buffer.write(Buffer.kt) at okhttp3.ResponseBody.create(ResponseBody.java:214) at okhttp3.internal.Util.(Util.java:69) at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313) at okhttp3.HttpUrl.get(HttpUrl.java:917) at okhttp3.HttpUrl.parse(HttpUrl.java:905) at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.(InfluxDBClientOptions.java:644) at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.(InfluxDBClientOptions.java:636) at com.influxdb.client.InfluxDBClientOptions$Builder.connectionString(InfluxDBClientOptions.java:471) at com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:274) at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:174) at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:149) at com.lanshancloud.service.SynchronousQuery.main(SynchronousQuery.java:19) Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 13 more
> 
> 2. Then when I try to reduce the version to 5.0.0, the exception does not exist and the program runs normally
> 
> **Expected behavior:** Show something, or perform it normally
> 
> **Actual behavior:** Exceptions were thrown
> 
> **Specifications:**
> 
> * Client Version:
>   com.influxdb
>   influxdb-client-java
>   6.0.0
> * InfluxDB Version: 2.0.7
> * JDK Version: 1.8.0_281
> * Platform: docker
> * development environment: Windows10 & IntelliJ IDEA 2021.3

![image](https://user-images.githubusercontent.com/27811560/164955434-b20d7446-89ec-4272-a46d-1f0f7c5ea0bc.png)
![image](https://user-images.githubusercontent.com/27811560/164955445-5713a36c-8260-478a-9774-210188181ed8.png)
![image](https://user-images.githubusercontent.com/27811560/164955452-bb6d43aa-8635-48e0-8557-a8709bd4c9e0.png)
 你可以试试这样。

**Comment by cuixin3266** [comment]
谢谢，问题解决了

**Comment by linghengqian** [comment]
I have to say that `influxdb-client-java` is the first version I have seen using okhttp `4.9.3`😆, I think this is enough to make a mark for `spring-boot-starter-parent`<`2.7.0-M2` in `README.md`  (after all, not who You can think of `okhttp` when you see an error from `Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at okio.Buffer.write(Buffer.kt)`, refer to the discussion at https://github.com/spring-projects/spring-boot/issues/18506#issuecomment-1016256152 )

**Comment by cuixin3266** [comment]
> I have to say that `influxdb-client-java` is the first version I have seen using okhttp `4.9.3`😆, I think this is enough to make a mark for `spring-boot-starter-parent`<`2.7.0-M2` in `README.md` (after all, not who You can think of `okhttp` when you see an error from `Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics at okio.Buffer.write(Buffer.kt)`, refer to the discussion at [spring-projects/spring-boot#18506 (comment)](https://github.com/spring-projects/spring-boot/issues/18506#issuecomment-1016256152) )

Your idea is great, if it wasn't for the help of the community, I might still be stuck with this problem, for the less experienced, this will save the mind

**Comment by bednar** [comment]
@linghengqian, @cuixin3266, @xx13295 

I am very grateful for your advice and comments. I've prepared the following update of documentation: https://github.com/influxdata/influxdb-client-java/pull/345.

Thanks again
