### ISSUE TITLE
WriteAPI Out Of Memory 

### ISSUE THREAD

**Issue by sq112358** [influxdata/influxdb-client-java#447]
Client Version: Cannot reuse and cannot release resources
InfluxDB Version: 2.0
Platform: mac OSX & CentOS

When I call getWriterApi the oom appears.Each time the method is called, a new instance is created

``Caused by: java.lang.OutOfMemoryError: unable to create new native thread
 at java.lang.Thread.start0(Native Method)
 at java.lang.Thread.start(Thread.java:717)
 at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
 at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603)
 at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
 at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
 at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:147)
 at io.reactivex.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:51)
 at io.reactivex.Scheduler$Worker.schedulePeriodically(Scheduler.java:433)
 at io.reactivex.internal.operators.flowable.FlowableWindowTimed$WindowExactBoundedSubscriber.onSubscribe(FlowableWindowTimed.java:340)
 at io.reactivex.internal.operators.flowable.FlowablePublishMulticast$MulticastProcessor.subscribeActual(FlowablePublishMulticast.java:297)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableWindowTimed.subscribeActual(FlowableWindowTimed.java:67)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.Flowable.subscribe(Flowable.java:14882)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
 at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.slowPath(FlowableFromArray.java:162)
 at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:90)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
 at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:38)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at com.influxdb.client.internal.AbstractWriteClient.lambda$null$2(AbstractWriteClient.java:133)
 at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.Flowable.subscribe(Flowable.java:14882)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
 at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.slowPath(FlowableFromArray.java:162)
 at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:90)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
 at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:38)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.Flowable.subscribe(Flowable.java:14882)
 at io.reactivex.internal.operators.flowable.FlowablePublishMulticast.subscribeActual(FlowablePublishMulticast.java:72)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.Flowable.subscribe(Flowable.java:14882)
 at io.reactivex.internal.operators.flowable.FlowableConcatMap.subscribeActual(FlowableConcatMap.java:66)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle.subscribeActual(FlowableConcatMapSingle.java:62)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe.subscribeActual(FlowableConcatMapMaybe.java:62)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.Flowable.subscribe(Flowable.java:14872)
 at io.reactivex.Flowable.subscribe(Flowable.java:14791)
 at com.influxdb.client.internal.AbstractWriteClient.<init>(AbstractWriteClient.java:175)
 at com.influxdb.client.internal.WriteApiImpl.<init>(WriteApiImpl.java:54)
 at com.influxdb.client.internal.InfluxDBClientImpl.getWriteApi(InfluxDBClientImpl.java:120)
 at com.influxdb.client.internal.InfluxDBClientImpl.getWriteApi(InfluxDBClientImpl.java:111)
 at com.test.sink.VictoriaMetricSink.invoke(VictoriaMetricSink.java:39)
 at com.test.sink.VictoriaMetricSink.invoke(VictoriaMetricSink.java:19)
 at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
 at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:233)
 at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134)
 at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105)
 at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496)
 at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761)
 at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
 at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
 at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
 at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
 at java.lang.Thread.run(Thread.java:748)``

**Comment by bednar** [comment]
Hi @sq112358,

thanks for using our client.

You have to use `getWriterApi` as a singleton. The `WriteApi` uses background thread to creates batches and ingesting data into InfluxDB. 

If you want to directly ingest data into InfluxDB you have to use _Synchronous blocking API_ - `getWriteApiBlocking()`.

For more info see:

- https://github.com/influxdata/influxdb-client-java/tree/master/client#synchronous-blocking-api
- https://github.com/influxdata/influxdb-client-java/tree/master/client#asynchronous-non-blocking-api

Regards
