### ISSUE TITLE
can not create organizations by code.

### ISSUE THREAD

**Issue by DamonDBT** [influxdata/influxdb-client-java#480]
i want to  do something as fellows:

1.  connect influxdb by the admin usename and password  
2. create oraganization by code. 

**but i can`t create client by username and password to connect the influxdb.**

my env is : jdk 1.8 ， win 10 ，jetbrain idea , influxdb oss 2.0, springboot maven project.

pom is :
```
      <dependency>
            <groupId>com.influxdb</groupId>
            <artifactId>influxdb-client-java</artifactId>
            <version>6.7.0</version>
        </dependency>

        <dependency>
            <groupId>com.influxdb</groupId>
            <artifactId>flux-dsl</artifactId>
            <version>6.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.6.10</version>
        </dependency>

```

here is my code.

```  
client = InfluxDBClientFactory.create(influxDBConfig.getServerURL(), username, pwd);
            OrganizationsApi organizationsApi = client.getOrganizationsApi();
            List<Organization> organizations = organizationsApi.findOrganizations();
            boolean haveOrgan=false;
            for (Organization organization : organizations) {
                if(organization.getName().equals(org)){
                    haveOrgan=true;
                     organizationsApi.updateOrganization(organization);
                }
            }
            if (!haveOrgan){
                Organization organization = organizationsApi.createOrganization(org);
            }
```

got error as line 1 :client = InfluxDBClientFactory.create(influxDBConfig.getServerURL(), username, pwd) :
```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.influxdb.client.internal.AuthenticateInterceptor.initToken(AuthenticateInterceptor.java:128)

The following method did not exist:

    okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

The method's class, okhttp3.RequestBody, is available from the following locations:

    jar:file:/D:/maven/java/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar!/okhttp3/RequestBody.class

It was loaded from the following location:

    file:/D:/maven/java/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of okhttp3.RequestBody

2022-12-09 14:24:59 JRebel: Reloading class 'com.ruoyi.level2.config.InfluxdConfig'.

```

**Comment by bednar** [comment]
Hi @DamonDBT,

thanks for using our client.

The client depends on `okhttp` v `4.10.0`. You have to upgrade your `okhttp` library.

Regards

**Comment by DamonDBT** [comment]
thanks for your answer , now i can connect db.
i connect to influxdb use admin user role , but when i  createOrganization , i got error :
why unauthorized ?
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.influxdb.client.InfluxDBClient]: Factory method 'influxDBClient' threw exception; nested exception is com.influxdb.exceptions.UnauthorizedException: HTTP status code: 401; Message: write:orgs is unauthorized
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)
	... 34 common frames omitted
Caused by: com.influxdb.exceptions.UnauthorizedException: HTTP status code: 401; Message: write:orgs is unauthorized
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:115)
	at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:84)
	at com.influxdb.client.internal.OrganizationsApiImpl.createOrganization(OrganizationsApiImpl.java:124)
	at com.influxdb.client.internal.OrganizationsApiImpl.createOrganization(OrganizationsApiImpl.java:109)
	at com.ruoyi.level2.config.InfluxdConfig.influxDBClient(InfluxdConfig.java:54)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1.CGLIB$influxDBClient$0(<generated>)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1$$FastClassBySpringCGLIB$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1.influxDBClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 common frames omitted

```

**Comment by bednar** [comment]
> i connect to influxdb use admin user role , but when i createOrganization , i got error :
> why unauthorized ?

Hard to say, it looks like issue in InfluxDB. Can you use the `admin` token? The authorization via token is preferred way.

**Comment by DamonDBT** [comment]
use token to connect:
url is : http://localhost:8086
some code is : 
```
  // client = InfluxDBClientFactory.create(url, username, pwd);
      client= InfluxDBClientFactory.create(url,influxDBConfig.getToken()  );
      OrganizationsApi organizationsApi = client.getOrganizationsApi();

 if (!haveOrgan){
            Organization organization = organizationsApi.createOrganization(org);
        }

```
also get same error:
```
Caused by: com.influxdb.exceptions.UnauthorizedException: HTTP status code: 401; Message: write:orgs is unauthorized
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:115)
	at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:84)
	at com.influxdb.client.internal.OrganizationsApiImpl.createOrganization(OrganizationsApiImpl.java:124)
	at com.influxdb.client.internal.OrganizationsApiImpl.createOrganization(OrganizationsApiImpl.java:109)
	at com.ruoyi.level2.config.InfluxdConfig.influxDBClient(InfluxdConfig.java:54)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1.CGLIB$influxDBClient$0(<generated>)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1$$FastClassBySpringCGLIB$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.ruoyi.level2.config.InfluxdConfig$$EnhancerBySpringCGLIB$$1.influxDBClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 common frames omitted
```
as you say , this may be a influxdb problem .
but what sense to use the method **createOrganization** ? or this method need more test ? 
thanks.

**Comment by bednar** [comment]
We have test for `createOrganization` and it works correctly - https://github.com/influxdata/influxdb-client-java/blob/5712b484f4874fada6fbd05454ef78b342f547d9/client/src/test/java/com/influxdb/client/ITOrganizationsApi.java#L66.

Try to generate new all scoped token.

**Comment by DamonDBT** [comment]
THX @bednar 

this is realy a problem with influxdb , 
when i use influxdb v2.0.8 , even i use ui ,i can only create one org at first init the influxdb.

after i upgrade to > V2.51 ,  the problem is gone, 
according to your this issue:
https://github.com/influxdata/influxdb/issues/11344
