### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by liulisanwan** [influxdata/influxdb-client-java#481]
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okio.Buffer.write(Buffer.kt)
	at okhttp3.ResponseBody.create(ResponseBody.java:214)
	at okhttp3.internal.Util.<clinit>(Util.java:69)
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.HttpUrl.parse(HttpUrl.java:905)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:689)
	at com.influxdb.client.InfluxDBClientOptions$Builder$ParsedUrl.<init>(InfluxDBClientOptions.java:681)
	at com.influxdb.client.InfluxDBClientOptions$Builder.connectionString(InfluxDBClientOptions.java:504)
	at com.influxdb.client.InfluxDBClientOptions$Builder.url(InfluxDBClientOptions.java:288)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:174)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:149)
	at com.influxdb.client.InfluxDBClientFactory.create(InfluxDBClientFactory.java:127)
	at com.test.InfluxDB2Example.main(InfluxDB2Example.java:14)

Can you help me?

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
