### ISSUE TITLE
SSL error connecting from Java

### ISSUE THREAD

**Issue by wise-coders** [influxdata/influxdb-client-java#594]
What could be wrong?

javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
  at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
  at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
  at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
  at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
  at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
  at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
  at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.client.internal.GzipInterceptor.intercept(GzipInterceptor.java:91)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:154)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.client.internal.AuthenticateInterceptor.intercept(AuthenticateInterceptor.java:103)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.internal.UserAgentInterceptor.intercept(UserAgentInterceptor.java:60)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:246)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:199)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:131)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:123)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:85)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:75)
  at com.wisecoders.dbschema.influxdb.InfluxMetaData.getSchemas(InfluxMetaData.java:31)
  at com.wisecoders.dbs.dbms.Dbms.listSchemasAndCatalogs(Dbms.java:287)
  at com.wisecoders.dbs.dbms.Dbms.loadSchemasAndCatalogs(Dbms.java:265)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.a(FxImportSelectionTask.java:41)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.call(FxImportSelectionTask.java:20)

com.influxdb.exceptions.InfluxException: Unsupported or unrecognized SSL message
  at com.influxdb.internal.AbstractQueryApi.lambda$static$1(AbstractQueryApi.java:89)
  at com.influxdb.internal.AbstractRestClient.catchOrPropagateException(AbstractRestClient.java:161)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:249)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:199)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:131)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:123)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:85)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:75)
  at com.wisecoders.dbschema.influxdb.InfluxMetaData.getSchemas(InfluxMetaData.java:31)
  at com.wisecoders.dbs.dbms.Dbms.listSchemasAndCatalogs(Dbms.java:287)
  at com.wisecoders.dbs.dbms.Dbms.loadSchemasAndCatalogs(Dbms.java:265)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.a(FxImportSelectionTask.java:41)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.call(FxImportSelectionTask.java:20)
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
  at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
  at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
  at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
  at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
  at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
  at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
  at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
  at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
  at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
  at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.client.internal.GzipInterceptor.intercept(GzipInterceptor.java:91)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:154)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.client.internal.AuthenticateInterceptor.intercept(AuthenticateInterceptor.java:103)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at com.influxdb.internal.UserAgentInterceptor.intercept(UserAgentInterceptor.java:60)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:246)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:199)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:131)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:123)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:85)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:75)
  at com.wisecoders.dbschema.influxdb.InfluxMetaData.getSchemas(InfluxMetaData.java:31)
  at com.wisecoders.dbs.dbms.Dbms.listSchemasAndCatalogs(Dbms.java:287)
  at com.wisecoders.dbs.dbms.Dbms.loadSchemasAndCatalogs(Dbms.java:265)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.a(FxImportSelectionTask.java:41)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.call(FxImportSelectionTask.java:20)

**Comment by bednar** [comment]
Hi @wise-coders,

thanks for using our client.

How do you configure connection url for the client? It looks like you try connect via `https` to serve without `SSL`.

Regards

**Comment by wise-coders** [comment]
Thank you, you are right.
