### ISSUE TITLE
UnauthorizedException after a while when connecting with influxdb-java [influxdb v2.0]

### ISSUE THREAD

**Issue by yyvus** [influxdata/influxdb-client-java#74]
We run an influxdb-java code that sinks data from kafka into the influxdb v2.0 database. The code works fine for a while (couple of days) and then suddenly throws the UnauthorizedException.

```
SEVERE: The error occurred during writing of data

com.influxdb.exceptions.UnauthorizedException: unauthorized access at
com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:98) at
com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:533) at
com.influxdb.client.internal.AbstractWriteClient.lambda$new$7(AbstractWriteClient.java:155) at
io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) at
io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284) at
io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137) at
io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.drain(FlowableConcatMapSingle.java:279) at
io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.innerSuccess(FlowableConcatMapSingle.java:179) at
io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber$ConcatMapSingleObserver.onSuccess(FlowableConcatMapSingle.java:317) at
io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) at
io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) at
io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119) at
io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120) at
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete(BasicFuseableConditionalSubscriber.java:119) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$State.checkTerminated(FlowableGroupBy.java:687) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:627) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:559) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$State.onComplete(FlowableGroupBy.java:549) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.onComplete(FlowableGroupBy.java:475) at
io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onComplete(FlowableGroupBy.java:213) at
io.reactivex.processors.UnicastProcessor.checkTerminated(UnicastProcessor.java:431) at
io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:314) at
io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:398) at
io.reactivex.processors.UnicastProcessor.onComplete(UnicastProcessor.java:488) at
io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.drain(FlowableWindowBoundary.java:237) at
io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.innerNext(FlowableWindowBoundary.java:149) at
io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryInnerSubscriber.onNext(FlowableWindowBoundary.java:281) at
io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360) at
io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:243) at
io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282) at
io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663) at
io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360) at io.reactivex.processors.PublishProcessor.offer(PublishProcessor.java:301) at
com.influxdb.client.internal.AbstractWriteClient.flush(AbstractWriteClient.java:171) at
PACKAGE.influxdb.sink.KafkaInfluxdbSink.transferData(KafkaInfluxdbSink.java:104) at
PACKAGE.influxdb.MainService.main(MainService.java:19)
```

Question: is there anyone else facing this difficulty and is there a timeout in the influxdb-java client authentication process. Because I found nothing in the influxdb documentation of the v1.7 and the v2.0 documentation seems not ready yet.

Moreover, I don't manage to identify the first `UnauthorizedException` since it works for a while. So I cannot relate this to an other exception that eventually occured before this one...

See the SO related question: [SO](https://stackoverflow.com/questions/59263154/influxdb-java-unauthorizedexception-after-a-while-influxdb-v2-0)

**Influxdb-java**:
```
                <dependency>
			<groupId>com.influxdb</groupId>
			<artifactId>influxdb-client-java</artifactId>
			<version>1.2.0</version>
		</dependency>
```

**Influxdb**: v2.0 alpha

**java**: openjdk 13.0.1

**Comment by yyvus** [comment]
I have then seen that there is an update on the maven repository 1.2.0 -> 1.3.0. I just pushed the update and will keep you informed on the effect.

**Comment by rhajek** [comment]
It is strange, can you provide more information about the environment ? 
What build of influxDB 2.0 you are using? Are you able to login into console on http://localhost:9999/ and verify that your auth token is valid ?
![image](https://user-images.githubusercontent.com/2169548/70627824-38c5a280-1c27-11ea-9e6b-84172047ddd0.png)

**Comment by yyvus** [comment]
Hi,

This is the version we use: `2.0.0-alpha.20_linux_arm64`. And yes we are able to login, the status is green.

**Comment by yyvus** [comment]
We have a better understanding now. The kafka broker we are connecting to has moments of inactivity: no producer produces data for a while. Then some producer restarts to operate and hence the influxdb sink too (polling again return messages). At that moment the influxdb java client sends this error message. Below a log at the moment this occurs:
```
 2019-12-20T14:05:08.682696418Z [32mINFO  2019 Dec 20, 14:05:08 [main] KafkaInfluxdbSink - No new record[m
 
I 2019-12-20T14:05:18.683154162Z [32mINFO  2019 Dec 20, 14:05:18 [main] KafkaInfluxdbSink - No new record[m
 
I 2019-12-20T14:05:28.682845861Z [32mINFO  2019 Dec 20, 14:05:28 [main] KafkaInfluxdbSink - No new record[m
 
I 2019-12-20T14:05:38.682812627Z [32mINFO  2019 Dec 20, 14:05:38 [main] KafkaInfluxdbSink - No new record[m
 
E 2019-12-20T14:05:44.944267862Z Dec 20, 2019 2:05:44 PM okhttp3.internal.platform.Platform log
 
E 2019-12-20T14:05:44.944308782Z INFO: --> POST https://wingman.enata.com/api/v2/write?org=enata&bucket=wingman&precision=ms (61-byte body)
 
E 2019-12-20T14:05:44.997612606Z Dec 20, 2019 2:05:44 PM okhttp3.internal.platform.Platform log
 
E 2019-12-20T14:05:44.997657632Z INFO: <-- 401 Unauthorized https://wingman.enata.com/api/v2/write?org=enata&bucket=wingman&precision=ms (53ms, 55-byte body)
 
E 2019-12-20T14:05:44.997973910Z Dec 20, 2019 2:05:44 PM com.influxdb.client.write.events.WriteErrorEvent logEvent
 
E 2019-12-20T14:05:44.997987718Z SEVERE: The error occurred during writing of data
 
E 2019-12-20T14:05:44.997994318Z com.influxdb.exceptions.UnauthorizedException: unauthorized access
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:98)
	at com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:533)
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$7(AbstractWriteClient.java:155)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.drain(FlowableConcatMapSingle.java:279)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.innerSuccess(FlowableConcatMapSingle.java:179)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber$ConcatMapSingleObserver.onSuccess(FlowableConcatMapSingle.java:317)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete(BasicFuseableConditionalSubscriber.java:119)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.checkTerminated(FlowableGroupBy.java:687)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:627)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:559)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.onComplete(FlowableGroupBy.java:549)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.onComplete(FlowableGroupBy.java:475)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onComplete(FlowableGroupBy.java:213)
	at io.reactivex.processors.UnicastProcessor.checkTerminated(UnicastProcessor.java:431)
	at io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:314)
	at io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:398)
	at io.reactivex.processors.UnicastProcessor.onComplete(UnicastProcessor.java:488)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.drain(FlowableWindowBoundary.java:237)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.innerNext(FlowableWindowBoundary.java:149)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryInnerSubscriber.onNext(FlowableWindowBoundary.java:281)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:243)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360)
	at io.reactivex.processors.PublishProcessor.offer(PublishProcessor.java:301)
	at com.influxdb.client.internal.AbstractWriteClient.flush(AbstractWriteClient.java:171)
	at com.enata.wingman.influxdb.sink.KafkaInfluxdbSink.transferData(KafkaInfluxdbSink.java:104)
	at com.enata.wingman.influxdb.MainService.main(MainService.java:19)
 
E 2019-12-20T14:05:44.998228224Z 
 
E 2019-12-20T14:05:44.998233715Z Dec 20, 2019 2:05:44 PM com.influxdb.client.internal.AbstractWriteClient close
 
E 2019-12-20T14:05:44.998239123Z INFO: Flushing any cached BatchWrites before shutdown.
 
E 2019-12-20T14:05:44.998560063Z Dec 20, 2019 2:05:44 PM okhttp3.internal.platform.Platform log
 
E 2019-12-20T14:05:44.998602504Z INFO: --> POST https://wingman.enata.com/api/v2/write?org=enata&bucket=wingman&precision=ms (61-byte body)
 
E 2019-12-20T14:05:45.001503994Z Dec 20, 2019 2:05:45 PM okhttp3.internal.platform.Platform log
 
E 2019-12-20T14:05:45.001529312Z INFO: <-- 401 Unauthorized https://wingman.enata.com/api/v2/write?org=enata&bucket=wingman&precision=ms (2ms, 55-byte body)
 
E 2019-12-20T14:05:45.001696343Z Dec 20, 2019 2:05:45 PM com.influxdb.client.write.events.WriteErrorEvent logEvent
 
E 2019-12-20T14:05:45.001714035Z SEVERE: The error occurred during writing of data
 
E 2019-12-20T14:05:45.001718510Z com.influxdb.exceptions.UnauthorizedException: unauthorized access
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:98)
	at com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:533)
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$7(AbstractWriteClient.java:155)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onNext(FlowableConcatMapMaybe.java:137)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.drain(FlowableConcatMapSingle.java:279)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.innerSuccess(FlowableConcatMapSingle.java:179)
	at io.reactivex.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber$ConcatMapSingleObserver.onSuccess(FlowableConcatMapSingle.java:317)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete(BasicFuseableConditionalSubscriber.java:119)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.checkTerminated(FlowableGroupBy.java:687)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:627)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:559)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$State.onComplete(FlowableGroupBy.java:549)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.onComplete(FlowableGroupBy.java:475)
	at io.reactivex.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onComplete(FlowableGroupBy.java:213)
	at io.reactivex.processors.UnicastProcessor.checkTerminated(UnicastProcessor.java:431)
	at io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:314)
	at io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:398)
	at io.reactivex.processors.UnicastProcessor.onComplete(UnicastProcessor.java:488)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.drain(FlowableWindowBoundary.java:237)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.innerNext(FlowableWindowBoundary.java:149)
	at io.reactivex.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryInnerSubscriber.onNext(FlowableWindowBoundary.java:281)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:243)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:360)
	at io.reactivex.processors.PublishProcessor.offer(PublishProcessor.java:301)
	at com.influxdb.client.internal.AbstractWriteClient.flush(AbstractWriteClient.java:171)
	at com.enata.wingman.influxdb.sink.KafkaInfluxdbSink.transferData(KafkaInfluxdbSink.java:104)
	at com.enata.wingman.influxdb.MainService.main(MainService.java:19)
```

**Comment by yyvus** [comment]
May I add that the influxdb sink is running on a google cloud.

**Comment by bednar** [comment]
Hi @yyvus,

we did a lot of improvements in our client. Could you test it with latest version?

Regards

**Comment by kiptix** [comment]
Hi!

I have the same problem. After maybe an hour (i dont know the exact timing or if it is always the same) i got the same error.
Restart of the client fixes the error. The client is a spring boot application. I am using the newest java client (1.12.0) und the rc-1 in an docker container.

**Comment by bednar** [comment]
Hi @kiptix,

Could you share a little bit more information how you use the client? Some piece of code?

Regards

**Comment by kiptix** [comment]
Hi @bednar 

here is almost all of the code:

```Java
@Repository
public class MeasuredValueInfluxRepository implements MeasuredValueRepository {

  private static final String TAG_ELEMENT_ID = "elementId";

  @Value("${spring.influx2.bucket}")
  private String bucket;

  @Autowired
  private InfluxDBClient influxDBClient;

  @Override
  public List<MeasuredValue> findByElementIdAndType(String elementId, MeasuredType type, Instant from, Instant to) {
    Restrictions restrictions = Restrictions.and(
        Restrictions.tag(TAG_ELEMENT_ID).equal(elementId),
        Restrictions.measurement().equal(type.name()),
        Restrictions.value().exists());

    Flux flux = Flux.from(bucket)
                    .range(from, to)
                    .filter(restrictions);

    return query(flux);
  }

  private List<MeasuredValue> query(Flux flux) {
    return influxDBClient.getQueryApi().query(flux.toString()).stream()
                         .map(FluxTable::getRecords).flatMap(Collection::stream)
                         .map(this::toMeasuredValue)
                         .filter(Objects::nonNull)
                         .collect(Collectors.toList());
  }

  private MeasuredValue toMeasuredValue(FluxRecord fluxRecord) {
    String elementId = (String) fluxRecord.getValueByKey(TAG_ELEMENT_ID);
    if (fluxRecord.getValue() != null) {
      return new MeasuredValue(
          elementId,
          fluxRecord.getTime(),
          MeasuredType.fromValue(fluxRecord.getMeasurement()),
          (double) fluxRecord.getValue());
    }
    return null;
  }
}
```

With these dependencies:
implementation "com.influxdb:influxdb-client-java:1.12.0"
implementation 'com.influxdb:influxdb-spring:1.12.0'
implementation 'com.influxdb:flux-dsl:1.12.0'

**Comment by bednar** [comment]
@kiptix thanks for detail info 👍 

Which version of InfluxDB do you use? Cloud or OSS?
Do you use token based authorization or username/password?

**Comment by kiptix** [comment]
@bednar It is the OSS Version in docker  with username and password 
But i have a second environment with an influxdb running as service (not in docker ), that is running for 2 days now and has no problems with the same Client. Maybe it is only a problem on my local machine or with docker.... 
So for me it is not longer a great problem, but if you need more information or someone to test, i try to help. If you can reproduce the problem at all ;)

**Comment by kiptix** [comment]
@bednar I think i found the problem in my local environment. My script in the docker container has created new tokens for the user on every start. So the user has multiple tokens for the same bucket. And that produces the "unauthorized access" at some point.
