### ISSUE TITLE
Integer value on writePoint

### ISSUE THREAD

**Issue by leonardo-belotti-aiknow** [influxdata/influxdb-client-java#792]
Hi everyone,
I'm using the client library in a Java 17 project.

Trying to add a simple point:
```
Map<String, Object> fields = new HashMap<>();
fields.put("id", 1L);
fields.put("name", "someName");
fields.put("originId", 1L);
fields.put("enumStatus", 1);
fields.put("message", "someMessage");

Point point = new Point("myMeasurement")
        .addFields(fields)
        .time(Instant.now().toEpochMilli(), WritePrecision.MS);
influxdb.writePoint(point);
```

with an enum value as _Integer_, I'm getting this error:
```
com.influxdb.exceptions.BadRequestException: HTTP status code: 400; Message: unable to parse 'myMeasurement enumStatus=1i,message="someMessage",originId=1i,name=someName,id=1i 1734422890042': invalid boolean
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:113) ~[influxdb-client-core-7.2.0.jar:7.2.0]
	at com.influxdb.internal.AbstractRestClient.toInfluxException(AbstractRestClient.java:99) ~[influxdb-client-core-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$8(AbstractWriteClient.java:174) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:85) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:238) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.mixed.ConcatMapXMainSubscriber.onNext(ConcatMapXMainSubscriber.java:106) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.drain(BackpressureBatchesBufferStrategy.java:238) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.onNext(BackpressureBatchesBufferStrategy.java:149) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.onNext(BackpressureBatchesBufferStrategy.java:54) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:232) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:150) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:75) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:53) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:270) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:627) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:103) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.accept(FlowableBufferTimedFlushable.java:227) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.accept(FlowableBufferTimedFlushable.java:85) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.subscribers.QueueDrainSubscriber.fastPathOrderedEmitMax(QueueDrainSubscriber.java:107) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.run(FlowableBufferTimedFlushable.java:281) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.core.Scheduler$Worker$PeriodicTask.run(Scheduler.java:543) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:80) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:71) ~[rxjava-3.1.9.jar:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

If I force the Integer `enumStatus` to `1L`, the insert succeed.

Am I missing something?

**Comment by bednar** [comment]
Hi @leonardo-belotti-aiknow,

Thank you for reaching out. To better assist you with the issue you’re encountering, it would be helpful if you could provide us with the debug output from the client’s communication. This information will allow us to see exactly what data is being sent and received, which is crucial for diagnosing communication or data handling issues.

Based on what you’ve described, it sounds like there might be a data type mismatch in your database schema. If your schema defines `enumStatus` as a `bool` and you are attempting to set this field with a value of 1i (which suggests an integer), this could indeed cause issues because InfluxDB would typically interpret 1 as true when expecting a boolean.

1/ Please verify the data types defined in your DB for the `enumStatus` field. 
2/ Please enable debugging in your client and provide the output here.

Best Regards.

**Comment by leonardo-belotti-aiknow** [comment]
Hi @bednar,
thank you for your answer.

1. I dropped the measurement to ensure that the parsed schema creates a new one
2. I don't have much output, just the error logged in my question

Update on the output:
```
2024-12-17T11:17:41.920+01:00 ERROR 5569 --- [keton] [eadScheduler-11] c.i.client.write.events.WriteErrorEvent  : An error occurred during writing of data.  Select Response Headers:
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.7.1


com.influxdb.exceptions.BadRequestException: HTTP status code: 400; Message: unable to parse 'myMeasurement enumStatus=1i,message="someMessage",originId=1i,name=someName,id=1i 1734430320001': invalid boolean
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:113) ~[influxdb-client-core-7.2.0.jar:7.2.0]
	at com.influxdb.internal.AbstractRestClient.toInfluxException(AbstractRestClient.java:99) ~[influxdb-client-core-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$8(AbstractWriteClient.java:174) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:85) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:238) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.mixed.ConcatMapXMainSubscriber.onNext(ConcatMapXMainSubscriber.java:106) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.drain(BackpressureBatchesBufferStrategy.java:238) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.onNext(BackpressureBatchesBufferStrategy.java:149) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.BackpressureBatchesBufferStrategy$OnBackpressureBufferStrategySubscriber.onNext(BackpressureBatchesBufferStrategy.java:54) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:232) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:150) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:75) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:53) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:270) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:627) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:103) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.accept(FlowableBufferTimedFlushable.java:227) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.accept(FlowableBufferTimedFlushable.java:85) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.internal.subscribers.QueueDrainSubscriber.fastPathOrderedEmitMax(QueueDrainSubscriber.java:107) ~[rxjava-3.1.9.jar:na]
	at com.influxdb.client.internal.flowable.FlowableBufferTimedFlushable$BufferExactBoundedSubscriber.run(FlowableBufferTimedFlushable.java:281) ~[influxdb-client-java-7.2.0.jar:7.2.0]
	at io.reactivex.rxjava3.core.Scheduler$Worker$PeriodicTask.run(Scheduler.java:543) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:80) ~[rxjava-3.1.9.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:71) ~[rxjava-3.1.9.jar:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na] 
```

and the fields of the POJO I'm converting to the `Map<String, Object>` are:
```
    @NotNull
    private Long id;

    @NotNull
    private long time;

    @NotNull
    private myStringEntityEnum name;

    @NotNull
    private Long originId;

    @NotNull
    private Long enumStatus;

    private String message;
```

converted like this:
```
        Map<String, Object> fieldsMap = new HashMap<>();
        fieldsMap.put("id", id);
        fieldsMap.put("name", name);
        fieldsMap.put("originId", originId);
        fieldsMap.put("enumStatus", enumStatus);
        fieldsMap.put("message", message);
```

Hope this can be more helpful

**Comment by leonardo-belotti-aiknow** [comment]
My fault. 

Here
```
com.influxdb.exceptions.BadRequestException: HTTP status code: 400; Message: unable to parse 'myMeasurement enumStatus=1i,message="someMessage",originId=1i,name=someName,id=1i 1734430320001': invalid boolean
```
I wasn't casting correctly the `name` field into `String`, so he has difficulty to cast.

Thank you!
We can close this issue.
